### ISSUE TITLE
MVP Decidim Vocdoni integration (1st iteration)

### ISSUE THREAD

**Issue by andreslucena** [decidim-vocdoni/decidim-module-vocdoni#4]
Since [at least 2019](https://contractaciopublica.gencat.cat/ecofin_pscp/AppJava/notice.pscp?mode=full&reqCode=viewCn&idDoc=44470951), the Decidim project has in its roadmap the need to have a method of expressing peoples opinions on a private and secure way. For different administrative reasons this couldn't be developed on a satisfactory way until now. We hope that through this integration we can have a component that give administrators an easy way to organize votings powered by the Vocdoni Protocol without the need for technical knowledge for the organizer and without leaving the Decidim interface.

Note that as this development is an MVP, so even though both Decidim and Vocdoni are mature products with dozens of features, we'll only handle the minimum to make the system work and from that we can have a better knowledge on  which other features we'll implement once we have the initial integration done. 

That means, these kind of features will not be in the first iteration of this development:

* Having different roles in Decidim
* Having a live census (aka adding new participants to the census after the election is created in Vocdoni API)
* In-person voting

As Decidim is currently in a big design revamp, we'll do the development starting from the last current stable release (v0.27).

In the past, Decidim already implemented some e-voting modules, such as:

1. `decidim-elections` (currently on development). Available at https://github.com/decidim/decidim/tree/develop/decidim-elections
2. `decidim-consultations` (currently deprecated in favor of `decidim-elections`). Available at https://github.com/decidim/decidim/tree/develop/decidim-consultations

As this is an MVP and `decidim-elections` is tightly coupled with the Election Guard stack (ie [Bulletin Board](https://github.com/decidim/decidim-bulletin-board)), we'll discard integrating this development in that module at least for the time being. This is something that can be developed in future iterations, although probably it'll need some refactoring (like extracting the current Bulletin Board logic to a module that implements a voting engine or provider).

---

# EPIC: Administrator

An administrator is a person that has to manage the platform, not from a technical point of view (sysadmin, programmer) but at the configuration level of the platform.

As an administrator, I want to ...
- [x] create a new election #5 
- [x] create a question with answers in an election #6
- [x] add a census to this election #7
- [x] set-up the Organization wallet #8 
- [x] set-up an election on Vocdoni API #9 
- [x] publish the results #10 

# EPIC: Voter

A voter is a participant registered in the census with right to vote in the electoral process. 

As a voter, I want to...
- [x] view the information for an election #11 
- [x] identify myself with the census #12 
- [x] submit a vote to the Vocdoni API  #13
- [x] verify a vote with the Vocdoni API #14
- [x] view the results  #15

**Comment by andreslucena** [comment]
Closing as all the issues related to this epic are merged already.
